theme: jekyll-theme-cayman


<!DOCTYPE html>
<html>
  <head>
   <title> 제천고등학교 금연 추진 사이트 </title>
   <meta charset = "utf-8"/>
  </head>
  <body>
    <h1> 제천고등학교 금연 추진 </h1>
    <p> JecheonHighSchool, No Smoking, GitHub, Atom </p>
    <img src="https://pds.joins.com/news/component/htmlphoto_mmdata/201501/01/htm_201501011221230103011.jpg" />
  </body>
</html>
